-- =====================================================================
-- GearRent — export the current database schema as SQL
-- Paste into the Supabase SQL Editor and run. It returns ONE cell
-- (schema_sql) containing the CREATE statements for everything in the
-- `public` schema plus the triggers on auth.users (the sign-up trigger).
-- Copy that cell into supabase_schema_dump.sql.
--
-- Not included: table data, table/function GRANTs (the gearrent_*.sql
-- migrations re-apply the ones that matter) and Storage policies (see
-- gearrent_supabase_storage_setup.sql).
-- =====================================================================

with
tbls as (
  select c.oid, c.relname, c.relrowsecurity
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relkind in ('r', 'p')
     and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'e')
),
stmts as (
  -- 1. Enum types
  select 1 as sec, t.typname::text as name,
         format('create type public.%I as enum (%s);', t.typname,
           (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
              from pg_enum e where e.enumtypid = t.oid)) as stmt
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
   where n.nspname = 'public' and t.typtype = 'e'

  union all
  -- 2. Sequences used by serial columns (identity columns create their own)
  select 2, c.relname::text, format('create sequence if not exists public.%I;', c.relname)
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'S'
     and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype in ('i', 'e'))

  union all
  -- 3. Tables and columns
  select 3, t.relname::text,
         format(E'create table public.%I (\n%s\n);', t.relname,
           (select string_agg(
                     format('  %I %s', a.attname, format_type(a.atttypid, a.atttypmod))
                     || case a.attidentity
                          when 'a' then ' generated always as identity'
                          when 'd' then ' generated by default as identity'
                          else '' end
                     || case
                          when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
                          when ad.adbin is not null then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
                          else '' end
                     || case when a.attnotnull then ' not null' else '' end,
                     E',\n' order by a.attnum)
              from pg_attribute a
              left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
             where a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped))
    from tbls t

  union all
  -- 4. Primary keys, unique and check constraints; 5. foreign keys (last,
  --    so every referenced table and key already exists)
  select case when con.contype = 'f' then 5 else 4 end,
         t.relname || '.' || con.conname,
         format('alter table public.%I add constraint %I %s;', t.relname, con.conname, pg_get_constraintdef(con.oid))
    from pg_constraint con
    join tbls t on t.oid = con.conrelid
   where con.contype in ('p', 'u', 'c', 'f', 'x')

  union all
  -- 6. Indexes that don't belong to a constraint
  select 6, i.relname::text, pg_get_indexdef(i.oid) || ';'
    from pg_index x
    join tbls t on t.oid = x.indrelid
    join pg_class i on i.oid = x.indexrelid
   where not exists (
     select 1 from pg_constraint con
      where con.conindid = x.indexrelid and con.conrelid = x.indrelid and con.contype in ('p', 'u', 'x')
   )

  union all
  -- 7. Functions
  select 7, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
         pg_get_functiondef(p.oid) || ';'
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.prokind in ('f', 'p')
     and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')

  union all
  -- 8. Views
  select 8, c.relname::text,
         format(E'create or replace view public.%I as\n%s', c.relname, pg_get_viewdef(c.oid, true))
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'v'
     and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'e')

  union all
  -- 9. Row level security
  select 9, t.relname::text, format('alter table public.%I enable row level security;', t.relname)
    from tbls t
   where t.relrowsecurity

  union all
  -- 10. Policies
  select 10, p.tablename || '.' || p.policyname,
         format('create policy %I on public.%I as %s for %s to %s%s%s;',
           p.policyname, p.tablename, p.permissive, p.cmd,
           (select string_agg(case when r::text = 'public' then 'public' else quote_ident(r::text) end, ', ')
              from unnest(p.roles) r),
           coalesce(' using (' || p.qual || ')', ''),
           coalesce(' with check (' || p.with_check || ')', ''))
    from pg_policies p
   where p.schemaname = 'public'

  union all
  -- 11. Triggers (public tables + the sign-up trigger on auth.users)
  select 11, c.relname || '.' || tg.tgname, pg_get_triggerdef(tg.oid) || ';'
    from pg_trigger tg
    join pg_class c on c.oid = tg.tgrelid
    join pg_namespace n on n.oid = c.relnamespace
   where not tg.tgisinternal
     and (n.nspname = 'public' or (n.nspname = 'auth' and c.relname = 'users'))
)
select string_agg(stmt, E'\n\n' order by sec, name) as schema_sql
  from stmts;
